server:
  port: 9002
spring:
  application:
    name: result-service
  datasource:
    url: jdbc:mysql://localhost:3307/soa_result?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: chung123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
<<<<<<< HEAD
      ddl-auto: none
=======
      ddl-auto: update
>>>>>>> 41f47cf6c68fde8de331b9e8db820850583a07ed
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
