server:
  port: 9003
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: qvchung0@gmail.com
    password: wrblwlnfnrslgiuw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
